### ISSUE TITLE
Heap size count is wrong in generated linker script

### ISSUE THREAD

**Issue by issuehsu** [sifive/freedom-devicetree-tools#176]
The generated heap info:
        .heap : {
                PROVIDE( metal_segment_heap_target_start = . );
                . = __heap_size;
                PROVIDE( metal_segment_heap_target_end = . );
                PROVIDE( _heap_end = . );

Which should be
                . += __heap_size;

**Comment by nick-knight** [comment]
I think this was resolved (as a non-issue) in #184 and #186.
